name: CI

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run forge build
        run: forge build --sizes

      - name: Run forge tests
        run: forge test -vvv
